#%RAML 1.0
title: Open TSDB API
version: v2.0
baseUri: https://docs.docker.com/engine/api/v1.33/
mediaType: application/json

/api/v1:
  displayName: v1 Api
  /put:
    displayName: Store Data Points
    post:
      queryParameters:
        summary: string
        details: string
        sync: boolean
        sync_timeout: integer
      headers:
        Authorization: string
      body: DataPoint[]
      responses:
        204:
        400:
          body: StorageResponse

types:
  DataPoint:
    type: object
    properties:
      metric: string
      timestamp: integer
      value: number
      tags:
        type: object

  StorageResponse:
    type: object
    properties:
      success: integer
      failed: integer
      errors: DataPointError[]

  DataPointError:
    type: object
    properties:
      datapoint: DataPoint
      error: string
