#%RAML 1.0
title: Microsoft Excel API
version: v1
description: Microsoft Excel API
baseUri: https://graph.microsoft.com/v1.0/me
mediaType: application/json

/drive:
  displayName: drive
  /{dir}:
    uriParameters:
      dir: string
    displayName: directory
  /items:
    displayName: items
    /{item}:
      displayName: item
      uriParameters:
        item: string
      delete:
        is: [microsoftGraphRequest]
        responses:
          204:
      /content:
        displayName: updateContent
        put:
          is: [microsoftGraphRequest]
          headers:
            Content-Type: string
          body:
            application/octet-stream:
              file
          responses:
            200:
              body: Workbook

      /workbook:
        displayName: workbook
        /worksheets:
          displayName: worksheets
          get:
            is: [microsoftGraphRequest]
            responses:
              200:
                body: WorksheetsResponseBody

          /add:
            displayName: add
            post:
              is: [microsoftGraphRequest]
              body: WorksheetPostBody
              responses:
                201:
                  body:
                    Worksheet

          /{worksheet}:
            displayName: worksheet
            uriParameters:
              worksheet: string

            /usedRange:
              displayName: usedRange
              get:
                is: [microsoftGraphRequest]
                responses:
                  200:
                    body: Range

            /cell(row={row},column={column}):
              displayName: cell
              uriParameters:
                row: integer
                column: integer
              get:
                is: [microsoftGraphRequest]
                responses:
                  200:
                    body: Range

            /tables:
              displayName: tables
              get:
                is: [microsoftGraphRequest]
                responses:
                  200:
                    body: TablesResponseBody
              /add:
                displayName: addTable
                post:
                  is: [microsoftGraphRequest]
                  body:
                    type: TableAddRequestBody
                  responses:
                    201:
                      body: Table

              /{table}:
                displayName: table
                uriParameters:
                  table: string

                delete:
                  is: [microsoftGraphRequest]
                  responses:
                    200:

                /rows/add:
                  displayName: rows
                  post:
                    is: [microsoftGraphRequest]
#                    body: RowPostBody
                    responses:
                      201:

                /columns:
                  displayName: columns
                  get:
                    is: [microsoftGraphRequest]
                    responses:
                      200:
                        body:  ColumnsGetResponseBody

                  post:
                    is: [microsoftGraphRequest]
                    body:
                      type: WorkbookTableColumn
                    responses:
                      201:
                        body: WorkbookTableColumn


            /range(address='{address}')/clear:
              displayName: rangeClear
              uriParameters:
                address: string
              post:
                is: [microsoftGraphRequest]
                body: ClearRequestBody
                responses:
                  204:

    "/{parent-id}:":
      displayName: parentId
      uriParameters:
        parent-id: string
      "/{filename}:":
        displayName: fileName
        uriParameters:
          filename: string
        /content:
          displayName: content
          put:
            is: [microsoftGraphRequest]
            headers:
              Content-Type: string
            body:
              application/octet-stream:
                file
            responses:
              200:
                body: Workbook
              201:
                body: Workbook

  /search(q='{q}'):
    uriParameters:
      q: string
    displayName: search
    get:
      is: [microsoftGraphRequest]
      responses:
        200:
          body: FilesResponseBody

annotationTypes:
  value-object-hint:
    type: string[]

traits:
  microsoftGraphRequest:
    headers:
      authorization: string
    responses:
      400:
        body: Error
      401:
        body: Error
      403:
        body: Error
      404:
        body: Error
      405:
        body: Error
      406:
        body: Error
      409:
        body: Error
      410:
        body: Error
      411:
        body: Error
      412:
        body: Error
      413:
        body: Error
      415:
        body: Error
      416:
        body: Error
      422:
        body: Error
      423:
        body: Error
      429:
        body: Error
      500:
        body: Error
      501:
        body: Error
      503:
        body: Error
      504:
        body: Error
      507:
        body: Error
      509:
        body: Error

types:
  Error:
    type: object
    properties:
      error:
        type: InnerError

  InnerError:
    type: object
    properties:
      code: string
      message: string
      innererror: InnerError

  FilesResponseBody:
    type: object
    properties:
      value: File[]
  File:
    type: object
    properties:
      id: string
      name: string
  WorksheetsResponseBody:
    type: object
    properties:
      value: Worksheet[]
  Worksheet:
    type: object
    properties:
      id: string
      name: string
      position: integer
  TablesResponseBody:
    type: object
    properties:
      value: Table[]
  Table:
    type: object
    properties:
      id: string
      name: string

  TableAddRequestBody:
    type: object
    properties:
      address: string
      hasHeaders: boolean

  ColumnsGetResponseBody:
    type: object
    properties:
      value:
        type: Column[]
  Column:
    type: object
    properties:
      id: string
      name: string

  ClearRequestBody:
    type: object
    properties:
      applyTo:
        enum: [All, Formats, Contents]

#  RowPostBody:
#    type: object
#    properties:
#      values:
#        type: Matrix
#
#  Matrix:
#    type: Line[]
#
#  Line:
#    type: array
#    items: string

  Workbook:
    type: object
    properties:
      id: string
      name: string
      size: integer
      file: file

  WorkbookTableColumn:
    type: object
    properties:
      id: string
      name: string
      index: integer
#      values: string

  WorksheetPostBody:
    type: object
    properties:
      name: string

  Range:
    type: object
    properties:
      address: string
      columnCount: integer
      columnIndex: integer
      rowCount: integer
      rowIndex: integer
